baseURL = "https://ala-alrababah.github.io/"
languageCode = "en-us"
title = ""
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "../ala-alrababah.github.io"

[params]
    author = "Ala' Alrababa'h"
    #description = "Personal blog theme powered by Hugo"
    githubUsername = "#"
    accent = "#2988CF"
    showBorder = false
    backgroundColor = "#F3F5F6"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/research/"
    name = "Research"
    weight = 2

[[menu.main]]
    url = "/cv/"
    name = "CV"
    weight = 3    

[[menu.main]]
    url = "/writing/"
    name = "Other Writing"
    weight = 4

[[menu.main]]
    url = "/data/"
    name = "Data"
    weight = 5
    
[[menu.main]]
    url = "/teaching/"
    name = "Teaching"
    weight = 6

#[[menu.main]]
#    url = "/media/"
#    name = "Arab Media"
#    weight = 7

#[[menu.main]]
#    url = "/post/"
#    name = "Posts"
#    weight = 7

#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 8

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:alaa@stanford.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/a_alrababah/"
    name = "twitter"
    weight = 2
