---
title: "Policy Writing"
output:
  html_document:
    toc: true
    toc_float: true
---

<br>

* [**Jordan shut out out 60,000 Syrian refugees and then saw a backlash. This is why**](https://www.washingtonpost.com/news/monkey-cage/wp/2018/07/20/when-jordan-closed-its-border-to-refugees-the-public-protested-heres-why/?utm_term=.8297c8ba5625) (with Scott Williamson). *Monkey Cage Blog, The Washington Post.* 2018. 

* [**Data Analysis: How did Jordanians Respond to the Formation of Al-Razzaz's Government?**](https://www.7iber.com/politics-economics/how-did-jordanians-respond-to-the-formation-of-al-razzazs-government-2/) *7iber.com.* 2018.

* [**Jordan's Danger Zone: The Perils of Building a Safe Haven in Syria.**](https://www.foreignaffairs.com/articles/jordan/2015-07-24/jordans-danger-zone) *Foreign Affairs.* 2015. 

* [**Jordan's Danger Zone: The Perils of Building a Safe Haven in Syria.**](https://www.foreignaffairs.com/articles/jordan/2015-07-24/jordans-danger-zone) *Foreign Affairs.* 2015. 

* [**Taking on Operation Dawn: The Creeping Advance of the Islamic State in Western Libya.**](https://carnegie-mec.org/diwan/60490?lang=en) (with Frederic Wehrey). *Diwan, Carnegie Endowment for International Peace.* 2015. 

* [**Splitting the Islamists: The Islamic State’s Creeping Advance in Libya.**](https://carnegie-mec.org/diwan/60447) (with Frederic Wehrey). *Diwan, Carnegie Endowment for International Peace.* 2015. 

* [**Rising Out of Chaos: The Islamic State in Libya**](https://carnegie-mec.org/diwan/59268) (with Frederic Wehrey). *Diwan, Carnegie Endowment for International Peace.* 2015. 

* [**Fighting Fire With Fire: Jordan’s Risky Strategy Against the Islamic State**](https://carnegie-mec.org/diwan/57486). *Diwan, Carnegie Endowment for International Peace.* 2014. 

* [**Saudi Rattles Its Saber**](https://www.nti.org/analysis/articles/saudi-rattles-its-saber/). (with Jeffrey Lewis). *Nuclear Threat Initiative.* 2014. 

* [**Jordan’s Transition to Democracy**](https://www.7iber.com/2011/07/jordans-transition-to-democracy/). *7iber.com.* 2011. 