---
title: "Research "
output:
  html_document:
    toc: true
    toc_float: true
---

<br>


<!---## Dissertation Project
Starting in late 2010, major uprisings across the Middle East toppled four of the world's longest serving dictators, creating hope  for democratization in several Arab countries. Prominent scholars and observants of the Middle East claimed that new technologies in media, primarily satellite TV and the internet, were essential for the success of the uprisings because they facilitated the spread of new ideas, avoided state censorship, and provided protest leaders with powerful tools to organize and mobilize effectively. A few years later, as democratization faltered across the region, scholars began to blame the media for playing a particularly destructive role in the political transitions that followed the uprisings, in particular because they were often used by regimes to counter reformist efforts and bring about an authoritarian resurgence. How did these authoritarian regimes learn to counter the effects of new media, and what did these efforts look like? More generally, how have autocrats responded to the loss of their monopoly over information that resulted from advances in media technology?

My dissertation project attempts to examine how Arab autocratic regimes responded to the rise of new media. I argue that autocrats adapted by using media to psychologically manipulate their publics. Before the proliferation of satellite television and internet media, autocrats had direct control over information through ownership of media organizations and censorship of unwanted articles. But once autocrats could no longer censor new media tools as effectively, they responded to this challenge by controlling available information in order to psychologically manipulate Arab publics. Specifically, autocrats use information to manipulate fear and optimism in ways that reduce the potential for domestic popular mobilization against the regime and influence foreign publics in ways that serve regime interests.

<br> -->

## Publications

**Maintaining Sovereignty and Preserving the Regime: How Saudi Arabia Views Strategic Stability** in Lawrence Rubin and Adam N. Stulberg, eds., *The End of Strategic Stability.* Georgetown University Press. 2018.

<br>

## Under Review

**[Attitudes toward Migrants in a Highly-Impacted Economy: Evidence from the Syrian Refugee Crisis in Jordan.](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3325362)** *Revise & Resubmit at Comparative Political Studies.*  
With Scott Williamson, Andrea Dillon, Jens Hainmueller, Dominik Hangartner, and Jeremy Weinstein.

With a record number of migrants moving across the globe, a burgeoning literature has explored the drivers of attitudes towards migrants. However, most major studies to date have focused on developed countries, which have relatively few migrants and substantial capacity to absorb them. We address this sample bias by conducting a large-scale representative survey of public attitudes toward Syrians in Jordan, a developing country with one of the largest shares of refugees. Our analysis indicates that neither personal nor community-level exposure to the economic impact of the refugee crisis is associated with anti-refugee sentiments among natives. Further, an embedded conjoint experiment demonstrates the relative importance of humanitarian and cultural over economic concerns. Taken together, our evidence weakens the case for labor market competition and sociotropic economic concerns as critical drivers of anti-migrant attitudes, and demonstrates how humanitarian motives can sustain support for refugees when host and migrant cultures are similar.  

<br>

**[Authoritarian Media and Diversionary Threats: Lessons from Thirty Years of Syrian State Discourse.](papers/authoritarian_media.pdf)** *Revise & Resubmit at Political Science Research and Methods.*  
With Lisa Blaydes.  

Scholars have long argued that leaders manipulate foreign policy, sometimes even initiating wars in order to enhance their domestic political position. But diversionary wars are relatively rare given the high costs of conflict. In this project, we examine data from major Syrian daily newspapers over a thirty-year period (1987-2018) to explore how autocratic regimes use diversionary rhetoric. We find that emphasis on Israel as a diversionary threat decreases during peace negotiations between Syria and Israel. Further, we find that before the Arab Uprisings, Syria's state-controlled media concentrated on Israel as a security and political threat. After 2011 scrutiny of Israel --- and other long-standing topics of state discourse --- was displaced by discussion of foreign plots and conspiracies against the Syrian state. Our analysis illustrates how authoritarian regimes make use of diversionary strategies as well as how political shocks generate discontinuities in authoritarian rhetoric.  

<br>

**Do Donor Motives Matter? Investigating Perceptions of Foreign Aid in the conflict in Donbas** *Revise & Resubmit at International Studies Quarterly.*  
With Rachel Myrick and Isaac Webb.

How do the perceived motives of donor states shape recipient attitudes towards foreign aid in a conflict zone? We identify two frames that characterize the motives of foreign powers involved in an ongoing civil conflict in the Donbas region of eastern Ukraine. These frames portray foreign actors as either providing aid to alleviate suffering during conflict (humanitarian frame) or to increase their power and influence in the recipient country (political influence frame). In a survey experiment conducted throughout Ukraine, we demonstrate how these frames impact attitudes towards foreign assistance from the European Union and the Russian government. We show that both frames increase support for foreign aid from the European Union but have no influence on views of Russian aid. Counter to conventional expectations, we demonstrate that aid provided for geopolitical, strategic reasons can at times be viewed as a positive, stabilizing force---even more than foreign aid provided for humanitarian reasons.  

<br>

**[Can Exposure to Celebrities Reduce Prejudice? Estimating the Effect of Mohamed Salah on Islamophobic Attitudes and Behaviors](https://osf.io/preprints/socarxiv/eq8ca/)** *Under Review*  
With William Marble, Salma Mousa, and Alexandra Siegel.  

* Selected media coverage: [BBC Arabic](https://twitter.com/BBCArabic/status/1142015205314125824), [The Economist](https://www.economist.com/britain/2019/06/06/mo-salahs-goals-help-to-tackle-islamophobia-in-liverpool), [The Times](https://www.thetimes.co.uk/article/mo-salah-success-scores-home-win-against-islamophobia-in-liverpool-6dnhttvp0), [Fox News](https://www.foxnews.com/sports/mohamed-salah-liverpool-islamophobia-study), [The Daily Mail](https://www.dailymail.co.uk/news/article-7102863/Islamophobia-plummeted-Liverpool-Egyptian-footballer-Mo-Salah-signed-researchers-say.html), [Sky News](https://news.sky.com/story/sky-views-football-fans-unity-has-enormous-power-to-drown-hatred-and-bile-11733823), [Vice](https://www.vice.com/en_us/article/qv7ev7/mo-salah-has-singlehandedly-reduced-islamophobia-in-liverpool), [The Independent](https://www.independent.co.uk/sport/football/news-and-comment/mohamed-salah-liverpool-islamophobia-muslim-goal-celebration-study-a8943501.html), [The National](https://www.thenational.ae/world/europe/mo-salah-may-have-caused-fall-in-islamophobia-in-liverpool-says-report-1.869695), [Spiegel Online](https://www.spiegel.de/panorama/mohamed-salah-fc-liverpool-stuermer-laesst-islamfeindlichkeit-sinken-a-1270644.html), [Le Figaro](http://www.lefigaro.fr/le-scan-sport/2019/06/05/27001-20190605ARTFIG00034-la-signature-de-salah-a-liverpool-aurait-provoque-une-baisse-des-crimes-anti-musulmans.php), [la Republica](https://www.repubblica.it/esteri/2019/06/06/news/il_calcio_che_unisce_a_liverpool_calano_attacchi_e_offese_anti-islam_grazie_a_salah-228076797/?fbclid=IwAR2YL0fQfljlx05PW0GXxdX06UneEHGQRKNYRgeM5O2GLb6HnbO1Vcu56sY&ref=RHPPBT-BH-I0-C4-P11-S1.4-T1), [Al Jazeera](https://www.aljazeera.net/news/humanrights/2019/6/3/%D8%AF%D8%B1%D8%A7%D8%B3%D8%A9-%D8%A8%D8%B1%D9%8A%D8%B7%D8%A7%D9%86%D9%8A%D8%A9-%D8%B5%D9%84%D8%A7%D8%AD-%D9%87%D8%B2%D9%85-%D8%A7%D9%84%D8%A5%D8%B3%D9%84%D8%A7%D9%85%D9%88%D9%81%D9%88%D8%A8%D9%8A%D8%A7-%D9%81%D9%8A-%D9%85%D8%B9%D9%82%D9%84-%D9%84%D9%8A%D9%81%D8%B1%D8%A8%D9%88%D9%84), [EuroNews](https://arabic.euronews.com/2019/06/03/swiss-report-says-salah-cuts-hate-crime-and-islamophobia-into-half-in-liverpool), [Al-Masry Al-Youm](https://www.almasryalyoum.com/news/details/1402243), [Al-Araby Al-Jadeed](https://www.alaraby.co.uk/medianews/2019/6/3/%d9%85%d8%ad%d9%85%d8%af-%d8%b5%d9%84%d8%a7%d8%ad-%d8%b3%d8%a7%d9%87%d9%85-%d8%a8%d8%a7%d9%86%d8%ae%d9%81%d8%a7%d8%b6-%d8%a7%d9%84%d8%a5%d8%b3%d9%84%d8%a7%d9%85%d9%88%d9%81%d9%88%d8%a8%d9%8a%d8%a7-%d9%81%d9%8a-%d9%84%d9%8a%d9%81%d8%b1%d8%a8%d9%88%d9%84). 

* [Webinar presentation here](https://www.dmeforpeace.org/media_gallery/me-thursday-talk-the-mo-salah-effect-can-exposure-to-celebrities-reduce-prejudice/?fbclid=IwAR38YxEC4v4xjVxl6D5AS5bQH7ENJKxa5EiEZM_XeHr1XMblIMtpRwj1uuQ) 

Can exposure to successful celebrities from stigmatized groups reduce prejudice toward that group at large? We exploit the sudden and phenomenal rise to faeme of Liverpool F.C. soccer star Mohamed Salah, a visibly Muslim player, to answer this question. We causally estimate the effect of Salah joining Liverpool F.C. on Islamophobic attitudes and behaviors using 936 county-month hate crime observations, 15 million tweets from U.K. soccer fans, and an original survey experiment of 8,060 Liverpool F.C. fans. We find that Merseyside county (home to Liverpool F.C.) experienced a 18.9% drop in hate crimes relative to a synthetic control, while no similar effect was found for other types of crime. We also find that Liverpool F.C. fans halved their rates of posting anti-Muslim tweets (a drop from 7.3% to 3.8% of tweets about Muslims) relative to fans of other top-flight English soccer clubs. The survey experiment suggests that these results may be driven by increased familiarity with Islam. Our findings indicate that positive exposure to outgroup role models can reveal new information that humanizes the outgroup writ large.

<br>

**To Pardon or to Prosecute? Experimental Evidence on Attitudes Towards Post-Conflict Justice** *Under Review*  
With Rachel Myrick


Scholars and practitioners debate the effectiveness of various strategies of post-conflict justice, but how do citizens impacted by conflict evaluate these policies? The conflict in eastern Ukraine presents an opportunity to shed light on public attitudes towards the “peace- versus-justice” debate. In a survey experiment fielded across Ukraine, including in the separatist-controlled areas, we provide respondents information about whether separatists or pro-government forces allegedly committed more war crimes during the conflict. We examine how this treatment impacts respondents’ evaluations of three post-conflict strategies: international trials, domestic trials, and amnesty policies. We find surprisingly little evidence that inter-group bias conditions attitudes towards these policies. Instead, our results demonstrate substantial support for international law. Ukrainians believe international law is more likely to bring both peace and justice, suggesting they are not mutually exclusive objectives. Our findings suggest international law may be particularly effective in post-conflict democracies where citizens perceive state institutions as weak or corrupt.

<br>

## Working Papers

**Using Transnational Media as a Soft Power Tool Evidence from Al-Arabiya and Al-Jazeera.** *Working Paper*

Since the end of the Cold War, the international relations literature has evolved to focus on non-traditional forms of power and competition. Perhaps most prominently, the study of soft power has shaped much of the academic literature and the policy world starting in the 1990s. Joseph Nye, who defined soft power as ``the ability to get what you want through attraction rather than coercion or payments,'' claimed that public diplomacy, including the use of media, is one of the most important tools of soft power. The vast majority of existing studies of soft power have either focused on democratic countries, like the U.S. and Europe, or fast growing countries, like China, as producers of attractive models. Scholars have paid little attention to Arab countries as producers of soft power because their autocratic nature and natural-resources-driven growth do not generate an attractive model. In this project, I examine how Saudi Arabia and Qatar have been using transnational media--specifically Al-Arabiya and Al-Jazeera--as soft power instruments. This study provides an original theory to explain how countries with limited attractive qualities can use the power of ideas to advance their interests and undermine enemies. I argue that, Qatar, which has faced regional hostility since the mid-1990s, has used Al-Jazeera to attract Arab publics to the idea of victimization in order to increase opposition to their regimes. Meanwhile, Saudi Arabia, a counter-revolutionary power, has used Al-Arabiya to pacify and depoliticize Arab publics. During diplomatic crises, these news sources can also directly undermine rivaling countries through negative coverage. I test this theory through an analysis of over 270,000 articles published in these platforms since 2014, as well as using qualitative examination of the articles.

<br>

**Call of Jihad or Call of Duty: Evaluating the Motives of Foreign Fighters in Iraq and Syria**

Over the past few decades, several civil wars have attracted a large number of foreign fighters. Most prominently, the ongoing Syrian civil war has drawn over 30,000 foreign fighters. While this influx has led to important policy questions, the topic remains largely understudied in political science. In this paper, I examine the motivations of foreign fighters by studying the effect of laws that criminalize foreign fighting. While laws are ineffective at preventing foreign fighters from traveling, they can have a differential effect on deterring foreign fighters depending on their motivations. Laws are unlikely to deter zealot fighters but they can deter adventure seekers from traveling to Iraq and Syria. In this paper, I use a difference-in-differences design to show that these laws have been an effective means for deterring potential foreign fighters from traveling to Iraq and Syria, thus suggesting that many foreign fighters are adventure seekers.

<br>

## Ongoing Projects

<br>

**The Enemy of my Enemy: How Autocrats Use Media to Manipulate Security Threats.**

<br>

**Credit Claiming and Blame Avoidance in Authoritarian Media** with Scott Williamson.

<br>

**Understanding the Dynamics of Refugee Return** with Daniel Masterson, Marine Casalis, Dominik Hangartner, and Jeremy Weinstein.

<br>

**State Immigration Policy and Immigrant Health** with Vicky Fouka, Jens Hainmueller, Dan Hopkins, Michael Hotard, Duncan Lawrence, and Rita Hamad.

<br>

**Permission to Secede? The Impact of Foreign Powers on Separatist Movements** with Rachel Myrick.

<br>

**Standards for Reporting Null Results** with Andrea Dillon, Scott Williamson, Jens Hainmueller, Dominik Hangartner, and Jeremy Weinstein.