---
title: '2020-05-02'
author: ~
date: '2020-05-02'
slug: 'news_2020-05-02'
categories: [regional]
tags: [covid19, egypt, jordan, yemen, corruption, uprisings, media, syria, russia, gulf, israel]
description: ''
---



### Al-Araby Al-Jadeed

[Corona Egypt: Doubts about the efficiency of the return-to-work plans](https://www.alaraby.co.uk/politics/2020/5/1/كورونا-مصر-شكوك-في-كفاءة-مخطط-العودة-للعمل)

The Egyptian government continues to rush towards a full return to service and financial activities after the end of the month of Ramadan, despite the worsening situation of the new Corona epidemic, the steady increase in the number of daily casualties... and the failure of the state to conduct random tests even in areas that witnessed high infection rates. 

<!-- [COVID-19; Egypt] --> 

[Public sector workers in Jordan fearful of being laid off](https://www.alaraby.co.uk/economy/2020/5/2/موظفو-القطاع-العام-الأردني-خائفون-من-تسريحهم)

The Jordanian government's decision to extend the leave for the public sector beyond Ramadan has raised the concerns of government workers, who are now afraid for the future of their jobs. This is especially in light of the government's tendencies to reduce the numbers of workers in the public sector.

<!-- [COVID-19; Jordan] --> 

[Recording the first infection with the Corona virus in Yemen's Taiz Governorate](https://www.alaraby.co.uk/society/2020/5/1/تسجيل-أول-إصابة-بفيروس-كورونا-في-محافظة-تعز-اليمنية)

On Friday, the Yemeni Ministry of Health announced recording the first case of the new corona virus in Taiz Governorate, bringing the total number of confirmed cases in the country to 7.

<!-- [COVID-19; Yemen] --> 

[When Rami Makhlouf begs Assad](https://www.alaraby.co.uk/opinion/2020/5/1/عندما-يستجدي-رامي-مخلوف-بشار-الأسد-1)

Op-ed describes conflict between Rami Makhlouf, Assad's cousin and business tycoon, who allegedly has Russia's support, and the Assad family--especially Asma' Al-Assad--which has Iran's support.

<!-- [Syria; corruption] --> 

[The upcoming Corona uprisings](https://www.alaraby.co.uk/opinion/2020/5/1/انتفاضات-كورونا-المقبلة-1)

Op-ed claims that a major economic crisis driven by COVID-19, and worsened by the drop in oil prices, and uncertainty about when the crisis will end could lead to major uprisings. This is especially given the bad economic situation and continued frustration of Arab publics since 2011 combined with the failure of recent uprisings in Iraq, Algeria, Lebanon, and Sudan to achieve their goals

<!-- [COVID-19; uprisings] --> 

[Media freedom and freedoms in Algeria: Are there any muzzles?](https://www.alaraby.co.uk/opinion/2020/5/1/حرية-الإعلام-والحريات-في-الجزائر-هل-من-كمامات-1)

Op-ed describes history and development of media freedom in Algeria, how it was limited under the former president, and continued restrictions since the recent uprising. 

<!-- [COVID-19; Algeria; Media freedom] --> 

[Russia and Assad](https://www.alaraby.co.uk/opinion/2020/5/1/روسيا-والأسد-1)

Michel Kilo discusses the rumours that Russia has decided to abandon Assad are true and suggests that he would prefer that Assad stays in power if his institutions are dismantled rather than Assad leaving but his institutions remaining.

<!-- [Syria; Russia] --> 

[How has the Israeli novel crept into Gulf drama?](https://www.alaraby.co.uk/entertainment/2020/5/2/كيف-تسللت-الرواية-الإسرائيلية-إلى-الدراما-الخليجية)

Article discusses evolution of television drama in the Gulf, oscillating between local societal issues and regional political issues--especially focusing on Israeli-Palestinian conflict. It then criticizes a recent trend in Gulf drama which calls for normalization with Israel and singles out two television dramas broadcasted by the Middle East Broadcasting Center, which is owned by the Saudis.

<!-- [Israel; Media; Gulf] --> 

[Palestinian anger at the dramas of normalization: What history is this?](https://www.alaraby.co.uk/entertainment/2020/5/2/غضب-الفلسطينيين-من-مسلسلات-التطبيع-أي-تاريخ-هذا)

Similar to previous article, discusses T.V. drama that call for normalization and Palestinian reactions to it. 

<!-- [Israel; Media; Gulf] --> 

<br>

### Al-Jazeera

[Congressional pressure to force Trump to reveal the name of Khashoggi's killer](https://www.aljazeera.net/news/politics/2020/5/2/أميركا-كونغرس-ترامب-جمال-خاشقجي)

Cites a buzzfeed article that discusses Congressional pressure on President Trump to reveal the name of Khashoggi's killer and suggests that Congress will block arms sales to Saudi Arabia until the names of the killers are revealed.

<br>

### Al-Arabiya

[Hidden torture cellars torture in Sanaa... a detainee describes "unbelievable atrocities"](https://www.alarabiya.net/ar/arab-and-world/yemen/2020/05/02/أقبية-تعذيب-خفية-في-صنعاء-معتقلة-تروي-فظائع-لا-تصدق-.html)

A network of secret prisons and cellars of torture affiliated with the Houthi militia is located in the Taiz neighborhood of Sana'a, camouflaged between schools and homes. It includes dozens of women who are subject to daily rape, beatings and torture by militia activists, as confirmed by Yemeni activists and former detainees in an investigation by the Associated Press. 

[Interrogating the world's richest person... and this is the list of accusations](https://www.alarabiya.net/ar/aswaq/companies/2020/05/02/استجواب-أغنى-أغنياء-العالم-وهذه-قائمة-الاتهامات.html)

The US House Judicial Committee summoned Amazon founder Jeff Bezos to testify before it because of "concerns about competition" related to the company's business practices.

[10 million riyals Saudi aid to the Palestinians to combat Corona](https://www.alarabiya.net/ar/saudi-today/2020/05/02/10-ملايين-ريال-مساعدات-السعودية-للفلسطينيين.html)

The Saudi Ambassador in Jordan, Naif Al-Sudairy, will launch a Saudi aid initiative to the Palestinian people to confront the Corona virus. This aid will value more than 10 million Saudi riyals, including medical devices and supplies that contracted by the King Salman Center for Relief and Humanitarian Work from Europe, China, and Saudi Arabia.

[The Mullahs threaten Trump with a surprise in October](https://www.alarabiya.net/ar/politics/2020/05/02/الملالي-يهددون-ترمب-بمفاجأة-في-أكتوبر.html)

With the Khomeinist regime in deep trouble again, the usual suspects launched a campaign to portray the Islamic Republic as a victim, and US President Donald Trump as the persecutor.

Fingers and blame have slowly shifted from the mullahs to the Trump administration, as the debate has been redirected to address the hypothetical question of US military action rather than addressing the real mistakes of the Islamic Republic.

Banners have appeared saying "No to war against Iran", although it would be more beneficial to say "No to wars by Iran." Others are claiming that the Mullahs are behaving badly because because Trump refuses to speak to them when in fact he has repeatedly said he is ready to speak to them anywhere and anytime.

[The Minister of Islamic Affairs in Saudi Arabia: The Brotherhood has a destructive project](https://www.alarabiya.net/ar/saudi-today/2020/05/01/وزير-الشؤون-الاسلامية-في-السعودية-للاخوان-مشروع-تدميري.html)

In a tweet, the Minister of Islamic Affairs in Saudi Arabia, Abdullatif Al-Sheikh, has asserted that the [Muslim] Brotherhood has a destructive project and that the group aims at destroying existing states to build their alleged state. 

<br>

### Sky News Arabia
[The beginning of the end of the Ottoman occupation of Egypt](https://www.skynewsarabia.com/blog/1340841-بداية-النهاية-للاحتلال-العثماني-لمصر)

They brag and say that the era of Muhammad Ali Pasha and his successors, as well as their achievements, should be credited to the Ottoman presence in Egypt. This narrative ignores that Muhammed Ali Pasha's rule over Egypt represented the strength of the Egyptian national will, despite the opposition of the Ottoman occupier, who did not stop his attempts to overthrow the governor. The governor's mandate from the beginning was the end of the Ottomans' brutal occupation.

<br>

### Al-Sharq Al-Awsat

[The prospects for the next Iranian revolution](https://aawsat.com/home/article/2263091/محمد-الرميحي/احتمالات-الثورة-الإيرانية-القادمة)
The American magazine "Foreign Affairs", which is influential in directing the policies of the United States has recently published a long study on "the necessity of working to change the Iranian regime." The study lists a large number of reasons that explain why regime change is a realistic plan. The study relied on a correct assumption: that after all these years, this regime in Iran has failed to respect international laws and provide its citizens with a minimum level of decent living.

[The ban for Hezbollah and the message to Iran](https://aawsat.com/home/article/2263086/إميل-أمين/الحظر-لـ«حزب-الله»-والرسالة-لإيران)

Better late than never. This appears to be the case in Europe with Hezbollah. After Britain last January, now it is Germany's turn, in a dramatic departure from the previous Berlin policy that was based on the position of the European Union.

[The State and human rights ... when the difference is made](https://aawsat.com/home/article/2263066/زهير-الحارثي/في-الدولة-وحقوق-الإنسان-عندما-يُصنع-الفارق)

Important recent reforms in Saudi Arabia improve human rights, include stopping the death sentence for those under 18 and replacing it with up to 10 years of prison in juvenile prison. Another reform includes stopping flogging and replacing it with prison sentencing or fines. Saudi is embarking on real reforms and not cosmetic procedures. These are internal decisions not driven by external pressures, which have existed for many years and have been ignored by Saudi Arabia. 